# Generated by Django 2.2 on 2021-09-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210919_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_duration_in_minutes',
            new_name='_appointment_duration_in_minutes',
        ),
    ]
