# Generated by Django 2.2 on 2021-09-19 06:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('specialty', models.CharField(choices=[('Bariatrics', 'Bariatrics'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Infectious disease', 'Infectious disease'), ('Pediatrics', 'Pediatrics')], max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=11)),
                ('opening_time', models.TimeField(default=datetime.time(8, 0))),
                ('closing_time', models.TimeField(default=datetime.time(21, 0))),
                ('appointment_duration_in_minutes', models.PositiveIntegerField(default=30)),
                ('description', models.CharField(blank=True, max_length=700, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
