# Generated by Django 2.2 on 2021-09-19 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Profile')),
                ('name', models.CharField(max_length=50)),
                ('specialty', models.CharField(choices=[('Bariatrics', 'Bariatrics'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Infectious disease', 'Infectious disease'), ('Pediatrics', 'Pediatrics')], max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=11)),
                ('opening_time', models.TimeField(default=datetime.time(8, 0))),
                ('closing_time', models.TimeField(default=datetime.time(21, 0))),
                ('appointment_duration_in_minutes', models.PositiveIntegerField(default=30)),
                ('description', models.CharField(blank=True, max_length=700, null=True)),
            ],
            bases=('user.profile',),
        ),
    ]
